import Head from 'next/head'
import { Poppins } from '@next/font/google'
import { Button, Container, Title } from '@mantine/core'

const inter = Poppins({
  subsets: ['latin'],
  weight: '600'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid py={20}>
        <Title className={inter.className} align='center' >Next Image Gallery</Title>
      </Container>
    </>
  )
}
